version: "3"

services:
  blog:
    image: node:18
    working_dir: /app
    command: npm run blog
    volumes:
      - .:/app
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
  e2e-tests:
    depends_on:
      blog:
        condition: service_healthy
    image: hydrofoil/hypertest:0.6.5
    network_mode: "host"
    environment:
      BASE_URI: "http://localhost:9000/"
    volumes:
      - ./test-e2e/blog:/tests
